export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILED = "LOGIN_FAILED"
export const REGISTER_FAILED = "REGISTER_FAILED"
export const LOAD_USER = "LOAD_USER"
export const AUTH_ERROR = "AUTH_ERROR"
export const LOG_OUT = "LOG_OUT"